import { FiClock, FiCpu, FiDatabase, FiLayers, FiShield, FiZap } from 'react-icons/fi'
import type { AskResponse } from '../../types/chat'
import { DrawerShell } from './DrawerShell'

const ms = (value?: number) => value == null ? '—' : `${Math.round(value)} ms`
export function InfoDrawer({ data, onClose }: { data: AskResponse | null; onClose: () => void }) {
  return <DrawerShell open={!!data} onClose={onClose} title="Response details" subtitle="Technical information for this answer">
    {data && <div className="info-content"><section className="confidence-card"><div><FiShield /><span>Confidence</span></div><strong>{Math.round(data.confidence_score * 100)}%</strong><div className="meter"><i style={{ width: `${Math.max(0, Math.min(100, data.confidence_score * 100))}%` }} /></div></section><div className="detail-grid"><Detail icon={<FiZap />} label="Provider" value={data.provider || '—'} /><Detail icon={<FiCpu />} label="Model" value={data.model_name || '—'} /><Detail icon={<FiDatabase />} label="Retrieval" value={ms(data.timings.retrieval_time_ms)} /><Detail icon={<FiClock />} label="Generation time" value={ms(data.timings.generation_time_ms)} /><Detail icon={<FiLayers />} label="Reranking" value={data.sources.length ? 'Enabled' : '—'} /><Detail icon={<FiLayers />} label="Chunks" value={`${data.sources.length}`} /></div><section className="sources"><h3>Sources <span>{data.sources.length}</span></h3>{data.sources.length ? data.sources.map((source) => <article key={`${source.chunk_id}-${source.rank}`}><div><strong>{source.source.split(/[\\/]/).pop()}</strong><small>Chunk ID · {source.chunk_id}{source.page_number ? ` · Page ${source.page_number}` : ''}</small><small>Reranker {source.reranker_score.toFixed(4)} · RRF {source.rrf_score.toFixed(4)}</small></div>{source.source_url && <a href={source.source_url} target="_blank" rel="noreferrer">Open</a>}</article>) : <p>No sources were returned.</p>}</section><section className="citations"><h3>Citations <span>{data.citations.length}</span></h3>{data.citations.length ? <ol>{data.citations.map((citation, index) => <li key={`${citation}-${index}`}>{citation}</li>)}</ol> : <p>No citations were returned.</p>}</section></div>}
  </DrawerShell>
}
function Detail({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="detail-item"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div> }
